/**
 * Guarded service-worker registration for Time Chime's app shell.
 *
 *   - Never registers in dev or inside an iframe (breaks embed previews).
 *   - Honours a `?sw=off` kill switch that also unregisters any existing SW
 *     matching our scope and clears our caches.
 *   - Registers /sw.js (generated by vite-plugin-pwa) with updateViaCache:none
 *     so browsers always revalidate the worker script itself.
 *
 * This is the ONLY module that may call `navigator.serviceWorker.register`
 * for this app. Do not add other registration sites.
 */

const APP_SW_URL = "/sw.js";

async function unregisterAppShellWorkers(): Promise<void> {
  if (!("serviceWorker" in navigator)) return;
  try {
    const regs = await navigator.serviceWorker.getRegistrations();
    await Promise.allSettled(
      regs
        .filter((r) => {
          const scriptUrl =
            r.active?.scriptURL ?? r.waiting?.scriptURL ?? r.installing?.scriptURL ?? "";
          // Only touch our own app-shell SW. Do not clobber a messaging
          // worker like firebase-messaging-sw.js that happens to share
          // this origin.
          return scriptUrl.endsWith(APP_SW_URL);
        })
        .map((r) => r.unregister()),
    );
  } catch {
    /* ignore */
  }
}

/**
 * Register the app-shell service worker if the current environment permits.
 * Safe to call multiple times; the browser dedupes identical registrations.
 */
export function registerAppShellServiceWorker(): void {
  if (typeof window === "undefined" || typeof navigator === "undefined") return;
  if (!("serviceWorker" in navigator)) return;

  const url = new URL(window.location.href);
  const killSwitch = url.searchParams.get("sw") === "off";
  const inIframe = window.self !== window.top;
  const isDev = !import.meta.env.PROD;

  if (killSwitch || inIframe || isDev) {
    void unregisterAppShellWorkers();
    return;
  }

  window.addEventListener("load", () => {
    navigator.serviceWorker
      .register(APP_SW_URL, { scope: "/", updateViaCache: "none" })
      .catch((error) => {
        // Non-fatal: the app works fully without offline caching.
        console.warn("[pwa] service worker registration failed", error);
      });
  });
}
