/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThirdPartyNoticesRouteImport } from './routes/third-party-notices'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SyncGuideRouteImport } from './routes/sync-guide'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as ObsRouteImport } from './routes/obs'
import { Route as BackgroundChimesRouteImport } from './routes/background-chimes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCspReportRouteImport } from './routes/api/public/csp-report'

const ThirdPartyNoticesRoute = ThirdPartyNoticesRouteImport.update({
  id: '/third-party-notices',
  path: '/third-party-notices',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncGuideRoute = SyncGuideRouteImport.update({
  id: '/sync-guide',
  path: '/sync-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsRoute = ObsRouteImport.update({
  id: '/obs',
  path: '/obs',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundChimesRoute = BackgroundChimesRouteImport.update({
  id: '/background-chimes',
  path: '/background-chimes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCspReportRoute = ApiPublicCspReportRouteImport.update({
  id: '/api/public/csp-report',
  path: '/api/public/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/background-chimes': typeof BackgroundChimesRoute
  '/obs': typeof ObsRoute
  '/offline': typeof OfflineRoute
  '/permissions': typeof PermissionsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap': typeof SitemapRoute
  '/support': typeof SupportRoute
  '/sync-guide': typeof SyncGuideRoute
  '/terms': typeof TermsRoute
  '/third-party-notices': typeof ThirdPartyNoticesRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/background-chimes': typeof BackgroundChimesRoute
  '/obs': typeof ObsRoute
  '/offline': typeof OfflineRoute
  '/permissions': typeof PermissionsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap': typeof SitemapRoute
  '/support': typeof SupportRoute
  '/sync-guide': typeof SyncGuideRoute
  '/terms': typeof TermsRoute
  '/third-party-notices': typeof ThirdPartyNoticesRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/background-chimes': typeof BackgroundChimesRoute
  '/obs': typeof ObsRoute
  '/offline': typeof OfflineRoute
  '/permissions': typeof PermissionsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap': typeof SitemapRoute
  '/support': typeof SupportRoute
  '/sync-guide': typeof SyncGuideRoute
  '/terms': typeof TermsRoute
  '/third-party-notices': typeof ThirdPartyNoticesRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/background-chimes'
    | '/obs'
    | '/offline'
    | '/permissions'
    | '/privacy'
    | '/sitemap'
    | '/support'
    | '/sync-guide'
    | '/terms'
    | '/third-party-notices'
    | '/api/public/csp-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/background-chimes'
    | '/obs'
    | '/offline'
    | '/permissions'
    | '/privacy'
    | '/sitemap'
    | '/support'
    | '/sync-guide'
    | '/terms'
    | '/third-party-notices'
    | '/api/public/csp-report'
  id:
    | '__root__'
    | '/'
    | '/background-chimes'
    | '/obs'
    | '/offline'
    | '/permissions'
    | '/privacy'
    | '/sitemap'
    | '/support'
    | '/sync-guide'
    | '/terms'
    | '/third-party-notices'
    | '/api/public/csp-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackgroundChimesRoute: typeof BackgroundChimesRoute
  ObsRoute: typeof ObsRoute
  OfflineRoute: typeof OfflineRoute
  PermissionsRoute: typeof PermissionsRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapRoute: typeof SitemapRoute
  SupportRoute: typeof SupportRoute
  SyncGuideRoute: typeof SyncGuideRoute
  TermsRoute: typeof TermsRoute
  ThirdPartyNoticesRoute: typeof ThirdPartyNoticesRoute
  ApiPublicCspReportRoute: typeof ApiPublicCspReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/third-party-notices': {
      id: '/third-party-notices'
      path: '/third-party-notices'
      fullPath: '/third-party-notices'
      preLoaderRoute: typeof ThirdPartyNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync-guide': {
      id: '/sync-guide'
      path: '/sync-guide'
      fullPath: '/sync-guide'
      preLoaderRoute: typeof SyncGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obs': {
      id: '/obs'
      path: '/obs'
      fullPath: '/obs'
      preLoaderRoute: typeof ObsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background-chimes': {
      id: '/background-chimes'
      path: '/background-chimes'
      fullPath: '/background-chimes'
      preLoaderRoute: typeof BackgroundChimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/csp-report': {
      id: '/api/public/csp-report'
      path: '/api/public/csp-report'
      fullPath: '/api/public/csp-report'
      preLoaderRoute: typeof ApiPublicCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackgroundChimesRoute: BackgroundChimesRoute,
  ObsRoute: ObsRoute,
  OfflineRoute: OfflineRoute,
  PermissionsRoute: PermissionsRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapRoute: SitemapRoute,
  SupportRoute: SupportRoute,
  SyncGuideRoute: SyncGuideRoute,
  TermsRoute: TermsRoute,
  ThirdPartyNoticesRoute: ThirdPartyNoticesRoute,
  ApiPublicCspReportRoute: ApiPublicCspReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
